Check if gosu is installed if su-exec is not available

diff --git a/rootfs/init-single b/rootfs/init-single
--- a/rootfs/init-single
+++ b/rootfs/init-single
@@ -5,10 +5,22 @@ if [[ -z "$@" ]]; then
     APP="bash"
 fi
 
-# Work out where su-exec is installed
-SUEXEC=$(command -v /sbin/su-exec)
-if [[ -z "$SUEXEC" ]]; then
-    SUEXEC=$(command -v /usr/bin/su-exec)
+# detect our privelage deescalation
+if command -v /sbin/su-exec > /dev/null
+then
+    SUEXEC="/sbin/su-exec"
+elif command -v /usr/bin/su-exec > /dev/null
+then
+    SUEXEC="/usr/bin/su-exec"
+elif command -v /usr/bin/gosu > /dev/null
+then
+    SUEXEC="/usr/bin/gosu"
+elif command -v /usr/sbin/gosu > /dev/null
+then
+    SUEXEC="/usr/sbin/gosu"
+else
+    echo "Unable to change process to default user"
+    exit 1
 fi
 
 exec /init "${SUEXEC}" app:app $APP
